PublicBodyCategories.add(:fr, [
	"Institutions principales",
    	[ "european_council", "Conseil européen", "Conseil européen" ],
    	[ "council_eu", "Conseil de l'Union européenne", "Conseil de l'Union européenne" ],
    	[ "european_parliament", "Parlement européen", "Parlement européen" ],
    	[ "court_justice", "Cour de Justice", "Cour de Justice" ],
    	[ "court_auditors", "Cour des comptes européenne", "Cour des comptes européenne" ],
	"Commision européenne",
    	[ "ec_dg", "Directions générales", "une Direction général de la Commision européenne"],
    	[ "ec_service", "Services de la Commision européenne", "un service de la Commision europénne"],
	"Autres institutions et organes principaux",
    	[ "eeas", "Service européen pour l’action extérieure", "Service européen pour l’action extérieure" ],
    	[ "eesc", "Comité économique et social européen", "Comité économique et social européen" ],
    	[ "committee_regions", "Comité des Régions", "Comité des Régions" ],
    	[ "eib", "Banque européenne d’investissement", "Banque européenne d’investissement" ],
    	[ "ecb", "Banque centrale européenne", "Banque centrale européenne" ],
    	[ "european_ombudsman", "Médiateur européen", "Médiateur européen" ],
    	[ "edps", "Contrôleur européen de la protection des données", "Contrôleur européen de la protection des données" ],
	"Autres agences et organismes",
    	[ "policy_agency", "Politique", "une agence liée aux politiques de l'UE "],
    	[ "security_agency", "Politique de sécurité et de défense commune", "Une agence pour la politique de sécurité et de défense commune"],
    	[ "judicial_agency", "Coopération policière et judiciaire en matière pénale", "une agence de coopération policière et judiciaire en matière pénale"],
    	[ "executive_agency", "Agences exécutives", "Une agence exécutif"],
    	[ "financial_supervisory", "Organismes de surveillance financière", "Un Organisme de surveillance financière"],
    	[ "euratom", "Agences et organes EURATOM", "Une agence EURATOM "],
    	[ "other", "Autres organismes", " "],
	"États membres",
    	[ "permanent_representative", "Représentants des États membres de l’UE", "Un représentant d’un état membre de l’UE"]
])
