PublicBodyCategories.add(:es, [
    "Principales instituciones",
    	[ "european_council", "Consejo Europeo", "Consejo Europeo" ],
    	[ "council_eu", "Consejo de la Unión Europea ", "Consejo de la Unión Europea" ],
    	[ "european_parliament", "Parlamento Europeo", "Parlamento Europeo" ],
    	[ "court_justice", "Tribunal de Justicia de la Unión Europea", "Tribunal de Justicia de la Unión Europea" ],
    	[ "court_auditors", "Tribunal de Cuentas de la UE", "Tribunal de Cuentas de la UE" ],
	"Comisión Europea",
    	[ "ec_dg", "Direcciones Generales de la Comisión", "una Dirección General de la Comisión Europea"],
    	[ "ec_service", "Servicios de la Comisión Europea", "un Servicio de la Comisión Europea"],
	"Otras instituciones y organismos",
    	[ "eeas", "Servicio Europeo de Acción Exterior", "Servicio Europeo de Acción Exterior"],
    	[ "eesc", "Comité Económico y Social Europeo", "Comité Económico y Social Europeo" ],
    	[ "committee_regions", "Comité de las Regiones", "Comité de las Regiones" ],
    	[ "eib", "Banco Europeo de Inversiones", "Banco Europeo de Inversiones" ],
    	[ "ecb", "Banco Central Europeo", "Banco Central Europeo" ],
    	[ "european_ombudsman", "Defensor del Pueblo Europeo", "Defensor del Pueblo Europeo" ],
    	[ "edps", "Supervisor Europeo de Protección de Datos", "Supervisor Europeo de Protección de Datos" ],
	"Otras Agencias y Organismos",
    	[ "policy_agency", "Política", "una Agencia de Política"],
    	[ "security_agency", "Política Común de Seguridad y Defensa", "una Agencia de Política Común de Seguridad y Defensa"],
    	[ "judicial_agency", "Cooperación policial y judicial", "una Agencia de Cooperación policial y judicial en materia penal"],
    	[ "executive_agency", "Agencias Ejecutivas", "una Agencia Ejecutiva"],
    	[ "financial_supervisory", "Organismos de supervisión financiera", "un Organismo de supervisión financiera"],
    	[ "euratom", "Agencias y organismos de EURATOM", "una agencia de EURATOM"],
    	[ "other", "Otros organismos", " "],
	"Estados Miembros",
    	[ "permanent_representative", "Representantes Permanentes de los Estados Miembros de la UE", "un Representante Permanente de un Estado Miembro de la UE"]
])
