PublicBodyCategories.add(:en, [
    "Main Institutions",
        [ "european_council", "European Council", "European Council" ],
        [ "council_eu", "Council of the European Union", "Council of the European Union" ],
        [ "european_parliament", "European Parliament", "European Parliament" ],
        [ "court_justice", "European Court of Justice", "European Court of Justice" ],
        [ "court_auditors", "European Court of Auditors", "European Court of Auditors" ],
    "European Commission",
        [ "ec_dg", "Commission Directorate Generals", "a European Commission Directorate General"],
        [ "ec_service", "European Commission Services", "a European Comission Service"],
    "Other Institutions and Key Bodies",
        [ "eeas", "European External Action Service", "European External Action Service" ],
        [ "eesc", "European Economic and Social Committee", "European Economic and Social Committee" ],
        [ "committee_regions", "Committee of the Regions", "Committee of the Regions" ],
        [ "eib", "European Investment Bank", " European Investment Bank" ],
        [ "ecb", "European Central Bank", "European Central Bank" ],
        [ "european_ombudsman", "European Ombudsman", "European Ombudsman" ],
        [ "edps", "European Data Protection Supervisor", "European Data Protection Supervisor" ],
    "Other Agencies and Bodies",
        [ "policy_agency", "Policy", "a Policy agency"],
        [ "security_agency", "Common Security and Defence Policy ", "a Common Security and Defence Policy agency"],
        [ "judicial_agency", "Police and Judicial Cooperation", "an agency for police and judicial cooperation in criminal matters"],
        [ "executive_agency", "Executive Agencies", "an Executive agency"],
        [ "financial_supervisory", "Financial supervisory bodies", "a financial supervisory body"],
        [ "euratom", "EURATOM Agencies and bodies", "an EURATOM agency"],
        [ "other", "Other bodies", " "],
    "Member States",
        [ "permanent_representative", "Permanent Representatives of Member States to the EU", "a permanent representative of a member state to the EU"]
])
