PublicBodyCategories.add(:en, [
    "Main Institutions",
        [ "xxx", "European Council", "European Council" ],
        [ "xxx", "Council of the European Union", "Council of the European Union" ],
        [ "xxx", "European Parlament", "European Parlament" ],
        [ "xxx", "European Commission", "European Commission" ],
        [ "xxx", "European Court of Justice", "European Court of Justice" ],
        [ "xxx", "European Court of Auditors", "European Court of Auditors" ],
    "Other Key Bodies",
        [ "xxx", "European External Action Service", "European External Action Service" ],
        [ "xxx", "European Economic and Social Committee", "European Economic and Social Committee" ],
        [ "xxx", "Committee of the Regions", "Committee of the Regions" ],
        [ "xxx", "European Investment Bank", " European Investment Bank" ],
        [ "xxx", "European Central Bank", "European Central Bank" ],
        [ "xxx", "European Ombudsman", "European Ombudsman" ],
        [ "xxx", "European Data Protection Supervisor", "European Data Protection Supervisor" ],
    "Member State Representatives",
    "European Commission bodies",
        [ "ec_departments", "Departments (DGs)", "an agency"],
        [ "ec_services", "European Commission Services", "an agency"],
    "Other Agencies",
        [ "policy_agencies", "Policy Agencies", "an agency"],
        [ "security_agencies", "Agencies for Common Security and Defence Policy ", "an agency"],
        [ "judicial_agencies", "Agencies for Police and Judicial Cooperation ", "an agency"],
        [ "executive_agencies", "Executive Agencies", "an agency"],
        [ "financial_supervision", "Financial supervisory bodies", "an agency"],
        [ "euratom", "EURATOM Agencies and bodies", "an agency"],
        [ "other", "Other bodies", "an agency"],
])
