PublicBodyCategories.add(:de, [
    "Hauptinstitutionen",
        [ "european_council", "Europäischer Rat", "Europäischer Rat" ],
        [ "council_eu", "Rat der Europäischen Union", "Rat der Europäischen Union" ],
        [ "european_parliament", "Europäisches Parlament", "Europäisches Parlament" ],
        [ "court_justice", "Europäischer Gerichtshof", "Europäischer Gerichtshof" ],
        [ "court_auditors", "Europäischer Rechnungshof", "Europäischer Rechnungshof" ],
    "Europäische Kommission",
        [ "ec_dg", "Generaldirektionen der Kommission", "eine Generaldirektion der Kommission"],
        [ "ec_service", "Dienstleistungen der Europäischen Kommission", "die Dienstleistung der Europäischen Kommission"],
    "Andere Behörden und zentrale Institutionen",
        [ "eeas", "Europäischer Auswärtiger Dienst", "Europäischer Auswärtiger Dienst" ],
        [ "eesc", "Europäischer Wirtschafts- und Sozialausschuss", "Europäischer Wirtschafts- und Sozialausschuss" ],
        [ "committee_regions", "Ausschuss der Regionen", "Ausschuss der Regionen" ],
        [ "eib", "Europäische Investitionsbank", " Europäische Investitionsbank" ],
        [ "ecb", "Europäische Zentralbank", "Europäische Zentralbank" ],
        [ "european_ombudsman", "Europäischer Bürgerbeauftragter", "Europäischer Bürgerbeauftragter" ],
        [ "edps", "Europäischer Datenschutzbeauftragter", "Europäischer Datenschutzbeauftragter"],
    "Andere Institutionen und Behörden",
        [ "policy_agency", "Richtlinie", "eine Fachagentur"],
        [ "security_agency", "Gemeinsame Sicherheits- und Verteidigungspolitik", "eine Institution der Gemeinsamen Sicherheits- und Verteidigungspolitik"],
        [ "judicial_agency", "Polizeiliche und justizielle Zusammenarbeit", "eine Agentur für die polizeiliche und justizielle Zusammenarbeit"],
        [ "executive_agency", "Exekutivagenturen", "eine Exekutivagentur"],
        [ "financial_supervisory", "Finanzaufsichtsbehörden", "eine Finanzaufsichtsbehörde"],
        [ "euratom", "Agenturen und sonstige Organe von EURATOM", "eine EURATOM Agentur"],
        [ "other", "andere Organe", " "],
    "Mitgliedsstaaten",
        [ "permanent_representative", "Permanente Vertreter der EU-Mitgliedsstaaten", "ein/e permanente/r Vertreter/in eines EU-Mitgliedsstaates"]
])
