PublicBodyCategories.add(:en, [
    "Main Institutions",
        [ "council", "European Council", "European Council" ],
        [ "council_eu", "Council of the European Union", "Council of the European Union" ],
        [ "parliament", "European Parliament", "European Parlament" ],
        [ "court_justice", "European Court of Justice", "European Court of Justice" ],
        [ "court_auditors", "European Court of Auditors", "European Court of Auditors" ],
    "Other Key Bodies",
        [ "external_action", "European External Action Service", "European External Action Service" ],
        [ "econ_soc_committee", "European Economic and Social Committee", "European Economic and Social Committee" ],
        [ "committee_regions", "Committee of the Regions", "Committee of the Regions" ],
        [ "investment_bank", "European Investment Bank", " European Investment Bank" ],
        [ "ecb", "European Central Bank", "European Central Bank" ],
        [ "ombudsman", "European Ombudsman", "European Ombudsman" ],
        [ "data_protection", "European Data Protection Supervisor", "European Data Protection Supervisor" ],
    "European Commission bodies",
        [ "ec_departments", "Departments (DGs)", "an agency"],
        [ "ec_services", "European Commission Services", "an agency"],
    "Other Agencies",
        [ "policy_agencies", "Policy Agencies", "an agency"],
        [ "security_agencies", "Agencies for Common Security and Defence Policy ", "an agency"],
        [ "judicial_agencies", "Agencies for Police and Judicial Cooperation ", "an agency"],
        [ "executive_agencies", "Executive Agencies", "an agency"],
        [ "financial_supervision", "Financial supervisory bodies", "an agency"],
        [ "euratom", "EURATOM Agencies and bodies", "an agency"],
        [ "other", "Other bodies", "an agency"],
    "Member State Representatives"
])
